# Generated by Django 5.2.4 on 2025-07-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='solo_empresas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.IntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Noche')], default=3),
        ),
    ]
