# Generated by Django 5.2.4 on 2025-07-30 02:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_curso_fecha_inicio_curso_solo_empresas_curso_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
